server:
    port: 8080
spring:
    datasource:
        data: classpath:db/data.sql
        schema: classpath:db/schema.sql
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/.h2/easy_ocr
        username: easy_ocr
        password: easy_ocr
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
