server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/.h2/easy_ocr
        username: easy_ocr
        password: easy_ocr
    sql:
        init:
            data-locations: optional:classpath:db/data.sql
            schema-locations: optional:classpath:db/schema.sql
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

logging:
    level:
        '[org.springframework.web.client.RestTemplate]': DEBUG
        '[org.example.easyocr]': DEBUG

openai:
    api:
        url: https://api.openai.com/v1/chat/completions
        key: sk-*** # Add your OpenAI API key here
    model: gpt-4o-mini
    prompt: "You are an OCR service. Your only task is to extract all visible text from this image. Return only the extracted text exactly as it appears, with original formatting when possible. Do not analyze, interpret, or add any commentary to the text."
    structured:
        prompt: "Extract all visible fields from this document (ID card, driver's license, etc.) and return ONLY a JSON object with field names in English and Keep the original value of the corresponding field."

app:
    http:
        connect-timeout: 30000 #in milliseconds
        read-timeout: 60000 #in milliseconds
    cors:
        allowed-origins: "*"